apiVersion: app.appvia.io/v2beta1
kind: AppComponent
metadata:
  name: demo-storage-account-app
spec:
  application: azure-demo
  container:
    containers:
    - env:
      - fromCloudResourceOutput:
          componentName: demo-storage-account
          output: PRIMARY_ACCESS_KEY
        name: AZURE_STORAGE_KEY
      - fromCloudResourceOutput:
          componentName: demo-storage-account
          output: NAME
        name: AZURE_STORAGE_ACCOUNT_NAME
      - fromCloudResourceOutput:
          componentName: demo-storage-account
          output: CONTAINER_NAME
        name: AZURE_CONTAINER_NAME
      image: ghcr.io/appvia/demo-storage-account-app:latest@sha-ade18e99336ccec4e5171eae052969da547c4df6
      name: ui
      ports:
      - containerPort: 3002
        name: ui
        protocol: TCP
      securityContext:
        runAsGroup: 999
        runAsUser: 999
    expose:
      container: ui
      port: 3002
    tls: true
  dependsOn:
  -  storage-account
  name: demo-storage-account-app
  type: Container
