apiVersion: app.appvia.io/v2beta1
kind: AppEnv
metadata: 
  name: azure-demo-dev
spec:
  name: dev
  stage: nonprod
  application: azure-demo
  cloud: azure
  clusterRef:
    group: compute.appvia.io
    kind: Cluster
    name: aks-d3c7e
    namespace: ws-demo
    version: v2beta1