apiVersion: app.appvia.io/v2beta1
kind: Application
metadata:
  name: azure-demo-app
spec:
  name: azure-demo-app
  cloud: azure
  components:
  - cloudResource:
      plan: appvia-azurerm-demo-storage-account
    type: CloudResource
    name: storage-account
  - container:
      env:
      - fromCloudResourceOutput:
          componentName: storage-account
          output: PRIMARY_ACCESS_KEY
        name: AZURE_STORAGE_KEY
      - fromCloudResourceOutput:
          componentName: storage-account
          output: NAME
        name: AZURE_STORAGE_ACCOUNT_NAME
      - fromCloudResourceOutput:
          componentName: storage-account
          output: CONTAINER_NAME
        name: AZURE_CONTAINER_NAME
      expose: true
      image: quay.io/appvia/demo-storage-account-app:latest
      port: 3002
      tls: true
    dependsOn:
    - storage-account
    name: azure-demo-app
    type: Container
