name: Develop
on:
  push:
    branches: 
      - main
env:
  REGISTRY: quay.io
  REGISTRY_ORG: appvia
jobs:
  image:
    runs-on: ubuntu-latest
    env:
      VERSION: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.WF_QUAY_IO_USERNAME }}
          password: ${{ secrets.WF_QUAY_IO_PASSWORD }}
      - name: Build and push image
        run: make docker-release
