name: Pull Request
on:
  pull_request:

env:
  REGISTRY: quay.io
  REGISTRY_ORG: appvia

jobs:
  image:
    runs-on: ubuntu-latest
    env:
      VERSION: pr${{ github.event.pull_request.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build image
        run: make docker
